language: generic
sudo: required
services:
    - docker
    
before_install:
    - docker build -t tsawyermissouri/docker-react -f Dockerfile.dev .
    
script:
    - docker run -e CI=true tsawyermissouri/docker-react npm run test    