language: generic
sudo: required
services:
    - docker
    
before_install:
    - docker build -t tsawyermissouri/docker-react -f Dockerfile.dev .
    
script:
    - docker run -e CI=true tsawyermissouri/docker-react npm run test    
    
deploy:
    edge: true
    provider: elasticbeanstalk
    region: "us-east-1"
    app: "docker-react"
    env: "DockerReact-env-1"
    bucket_name: "elasticbeanstalk-us-east-1-572725805796"
    bucket_path: "docker-react"
    on:
        branch: master    
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    